version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    image: elhawary22/auth-service:latest          # ← أضف سطر image ده
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce_db

  product-service:
    image: elhawary22/product-service:latest       # ← أضف
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce_db
    volumes:
      - ./product-service/uploads:/app/uploads

  display-service:
    image: elhawary22/display-service:latest       # ← أضف
    build: ./display-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce_db

  frontend:
    image: elhawary22/frontend:latest              # ← أضف
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - display-service

volumes:
  mongo-data:
